FROM byuoitav/arm32v6-alpine
MAINTAINER Tony Petrangelo <tonypetrangelo@gmail.com>

ARG NAME
ENV name=${NAME}

COPY ${name}-arm ${name}-arm
COPY version.txt version.txt

# add any required files/folders here

ENTRYPOINT ./${name}-arm
